name: Update services data

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  fetch:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run generate
        continue-on-error: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 🤖 Update service data (push to main)
          add_options: '-u' # Don't add untracked files
