name: Update services data

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  fetch:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CHAIN_WORKFLOW_PAT }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run fetch-and-update
      - run: npm run generate
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 🤖 Update service data (push to main)
          file_pattern: 'data website'
